### ISSUE TITLE
Fash dataset

### ISSUE THREAD

**Issue by Tmyann** [davidstutz/superpixel-benchmark#10]
Hi, thanks for your work!
The Fash dataset cannot be downloaded via the link. I don't know if it is the problem of my network. Do you have a backup of this dataset?

**Comment by Tmyann** [comment]
I have found another link to the dataset, thanks anyway!

**Comment by davidstutz** [comment]
For me the official link [1] works fine.

[1] http://vision.is.tohoku.ac.jp/~kyamagu/research/clothing_parsing/
