### ISSUE TITLE
Missing ^2 in the denominator of the equation 6 in the v3 of the paper on ArXiv

### ISSUE THREAD

**Issue by slackmate** [davidstutz/superpixel-benchmark#2]
Hi,

I believe there is a missing `^2` in the denominator of the equation 6 in the v3 of the paper dated 19 April 2017. This is in section 5 - Benchmark - in the calculation of Compactness CO. The denominator should be `P^2(Sj)`. Reference [43] also contains `^2`.

Kind regards

**Comment by RoyiAvital** [comment]
Hi,

you may add https://ieeexplore.ieee.org/document/8360143/

**Comment by davidstutz** [comment]
Yes, you are right, missed that and even did not notice it for the published version.

@RoyiAvital: feel free to get in touch if you have results for this algorithm. I will not be able to adapt and evaluate it myself.
