### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by amiratag** [davidstutz/superpixel-benchmark#3]
Hi, great work! I was wondering which data sets do you recommend for fast visual evaluation of a new method which also has the most inclusive licensing?

**Comment by davidstutz** [comment]
Sorry for the very late answer! I would always recommend BSDS500 as it is the smallest and quite standard. However, the licensing is somewhat unclear. Unfortunately, this holds for most of the datasets. If you check the web pages or even the downloads you won't find any "proper" license. As long as you use it for research, though, you should be safe.
