### ISSUE TITLE
Compatibility with OpenCV

### ISSUE THREAD

**Issue by skn123** [davidstutz/superpixel-benchmark#4]
Can the code be modified to be compatible with OpenCV 4.0?

**Comment by davidstutz** [comment]
Sorry for the very late answer!

I haven't used OpenCV in quite a while, so I do not feel comfortable giving a definite answer. You might have difficulties with the utilities. However, most of the algorithms are actually implemented in a stand-alone fashion and I only added OpenCV wrappers around them, so you should be able to adapt the wrappers to OpenCV 4 and the algorithms should still work. Evaluation, however, is based more heavily on OpenCV.
