### ISSUE TITLE
The meaning of measures in parameter optmization file

### ISSUE THREAD

**Issue by kaiwensophie** [davidstutz/superpixel-benchmark#5]
Hi,
I'm working on the parameter optimization of superpixels. After run the eval_parameter_optimization_cli command, the metrics for different parameters, and the optimal parameters are listed in parameter_optimazation.csv file. In this file, I wonder what does score, co_score, and sp_average mean.  And what is the difference between best and co_best?  Thank you.

**Comment by davidstutz** [comment]
The score is the average of UE and Boundary Recall, that's what we optimized for (see here: https://github.com/davidstutz/superpixel-benchmark/blob/master/lib_eval/parameter_optimization_tool.cpp#L408). Similary you can find the other metrics in the same file, e.g. here for co_score: https://github.com/davidstutz/superpixel-benchmark/blob/master/lib_eval/parameter_optimization_tool.cpp#L442.
